# Generated by Django 4.0.5 on 2023-06-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('send_time', models.DateField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('scenery_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('people_percent', models.CharField(blank=True, max_length=32, null=True)),
                ('play_time', models.CharField(blank=True, max_length=64, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('scenery_name', models.CharField(blank=True, max_length=64, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('evaluates', models.ManyToManyField(to='mainapp.evaluate')),
            ],
        ),
    ]
