# Generated by Django 4.0.5 on 2023-05-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_userinfo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
