# Generated by Django 4.0.5 on 2023-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('send_time', models.TextField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('scenery_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('people_percent', models.TextField(blank=True, null=True)),
                ('play_time', models.TextField(blank=True, null=True)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('scenery_name', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('evaluates', models.ManyToManyField(to='warehouse.evaluate')),
            ],
        ),
    ]
