# Generated by Django 4.0.5 on 2023-05-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_spiderlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpiderLog',
        ),
    ]
