# Generated by Django 4.0.5 on 2023-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_delete_spiderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spider_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
