# Generated by Django 4.0.5 on 2023-05-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_spiderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='scenery_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='send_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='user_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='people_percent',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='play_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='scenery_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
